version: '3.4'

services:
  sso:
    image: mernat/gosso:latest
    ports:
      - '8080:8080'
    depends_on:
      - postgres
  
  postgres:
    image: mernat/sso-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sso
